"""Conversational orchestration for the local FEM package."""

from __future__ import annotations

from .authoring import (
    AUTHORING_SCHEMA_VERSION,
    AgentDraft,
    AgentProposal,
    AuthoringContext,
    FakeAuthoringPort,
    LocalModelBinding,
    ModelPatch,
    RequirementLedger,
    RequirementReview,
    UnitContextSummary,
)
from .analysis_authoring import (
    AnalysisAuthoringError,
    ConfirmedDisplacement,
    ConfirmedLoad,
    ConfirmedResultRequest,
    LinearStaticAnalysis,
    create_analysis_definition_change,
)
from .geometry_authoring import (
    GeometryDraft,
    StaticGeometryPreview,
    box_geometry,
    create_geometry_proposal,
    cylinder_geometry,
    disk_geometry,
    plate_with_hole_geometry,
    rectangle_geometry,
    rotate_geometry,
    translate_geometry,
)
from .definition_authoring import (
    PlateScopeSet,
    ScopeSelectionError,
    ScopeSelectionEvidence,
    build_eccentric_plate_scopes,
    create_scope_definition_change,
)
from .naming import NameAllocator, NamePolicy
from .mesh_authoring import (
    MESH_INTENT_SCHEMA_VERSION,
    MeshIntent,
    create_mesh_proposal,
)
from .solve_authoring import (
    SolveAuthoringError,
    SolveSummary,
    SolveValidationStamp,
    build_solve_summary,
    create_solve_proposal,
    solve_operation_identity,
    validation_stamp_for_snapshot,
)
from .result_authoring import (
    RESULT_CATALOG_TOOL_NAME,
    RESULT_QUERY_SCHEMA_VERSION,
    RESULT_QUERY_TOOL_NAME,
    AcceptedResultSource,
    AgentResultAggregation,
    AgentResultCatalog,
    AgentResultCatalogResponse,
    AgentResultDiagnostic,
    AgentResultField,
    AgentResultLocation,
    AgentResultQuery,
    AgentResultQueryBridge,
    AgentResultQueryPort,
    AgentResultQueryResponse,
    AgentResultScalar,
    AgentResultVariable,
    FakeAgentResultQueryPort,
    ResultAuthoringError,
    explain_result_response,
    result_catalog_tool_schema,
    result_query_tool_schema,
)
from .schemas import SCHEMA_VERSION

__all__ = [
    "AUTHORING_SCHEMA_VERSION",
    "AgentDraft",
    "AgentProposal",
    "AnalysisAuthoringError",
    "AcceptedResultSource",
    "AgentResultAggregation",
    "AgentResultCatalog",
    "AgentResultCatalogResponse",
    "AgentResultDiagnostic",
    "AgentResultField",
    "AgentResultLocation",
    "AgentResultQuery",
    "AgentResultQueryBridge",
    "AgentResultQueryPort",
    "AgentResultQueryResponse",
    "AgentResultScalar",
    "AgentResultVariable",
    "AuthoringContext",
    "ConfirmedDisplacement",
    "ConfirmedLoad",
    "ConfirmedResultRequest",
    "FakeAuthoringPort",
    "FakeAgentResultQueryPort",
    "LocalModelBinding",
    "LinearStaticAnalysis",
    "NameAllocator",
    "NamePolicy",
    "MESH_INTENT_SCHEMA_VERSION",
    "MeshIntent",
    "ModelPatch",
    "PlateScopeSet",
    "RequirementLedger",
    "RequirementReview",
    "RESULT_CATALOG_TOOL_NAME",
    "RESULT_QUERY_SCHEMA_VERSION",
    "RESULT_QUERY_TOOL_NAME",
    "ResultAuthoringError",
    "ScopeSelectionError",
    "ScopeSelectionEvidence",
    "SolveAuthoringError",
    "SolveSummary",
    "SolveValidationStamp",
    "GeometryDraft",
    "StaticGeometryPreview",
    "UnitContextSummary",
    "box_geometry",
    "build_eccentric_plate_scopes",
    "build_solve_summary",
    "create_scope_definition_change",
    "create_analysis_definition_change",
    "create_mesh_proposal",
    "create_solve_proposal",
    "create_geometry_proposal",
    "cylinder_geometry",
    "disk_geometry",
    "explain_result_response",
    "plate_with_hole_geometry",
    "rectangle_geometry",
    "result_catalog_tool_schema",
    "result_query_tool_schema",
    "rotate_geometry",
    "solve_operation_identity",
    "translate_geometry",
    "validation_stamp_for_snapshot",
    "SCHEMA_VERSION",
]

__version__ = "0.1.0"
