"""Analysis compilation, procedures, increment control, and result publishing."""

from . import incremental, linear_static

from .contracts import AnalysisRequest, AnalysisRequestFactory, NonlinearStaticAnalysis
from .compiled import CompiledAnalysis, CompiledSystem
from .execution_plan import (
    AnalysisExecutionPlan,
    ExecutionStrategy,
    execution_plan_cache_scope,
    resolve_execution_plan,
)
from .compiler import compile_analysis
from .procedures import (
    AnalysisPath,
    AnalysisExecutor,
    AnalysisProcedure,
    AnalysisProcedureRegistry,
    DEFAULT_ANALYSIS_EXECUTOR,
    DEFAULT_ANALYSIS_PROCEDURES,
    ExplicitDynamicProcedure,
    ImplicitDynamicProcedure,
    LinearStaticProcedure,
    LinearDynamicProcedure,
    NonlinearStaticProcedure,
    PreparedAnalysis,
    ProcedureContext,
    RegisteredAnalysisExecutor,
    analysis_path_for,
    materialize_incremental_result,
)
from .runner import AnalysisCancelled, check_cancelled, run_compiled_analysis
from .compilation.boundary.compiled import CompiledBoundary, compile_boundary
from .compilation.materials import (
    CompiledMaterialAssignment,
    CompiledMaterialAssignments,
    compile_material_assignments,
)
from .resolution import (
    is_nlgeom_enabled,
    require_nlgeom,
    resolve_analysis_request,
    resolve_geometry_mode,
    resolve_formulation,
    resolve_nlgeom,
)
from .validation import (
    validate_analysis_step,
    validate_mesh,
    validate_model,
    validate_model_structure,
)
from .compilation.assignments import (
    EffectiveSectionAssignment,
    ResolvedSectionAssignment,
    SectionResolution,
    SectionResolutionIssue,
    apply_sections,
    restored_element_properties,
    resolve_sections,
)
from .compilation.sections import (
    BEAM_SECTION_TYPES,
    SECTION_PRESETS,
    SECTION_TYPES,
    MaterialPropertyError,
    ResolvedSectionProperties,
    SectionCompatibilityError,
    SectionPropertyError,
    SectionSchemaError,
    element_section_family,
    resolve_section_properties,
    resolve_section_preset_properties,
    section_family,
    section_presets_for_element_family,
    section_type_for_preset,
    validate_material_properties,
)

__all__ = [
    "AnalysisProcedure",
    "AnalysisExecutor",
    "AnalysisRequestFactory",
    "AnalysisRequest",
    "AnalysisExecutionPlan",
    "AnalysisPath",
    "ExecutionStrategy",
    "execution_plan_cache_scope",
    "AnalysisProcedureRegistry",
    "DEFAULT_ANALYSIS_PROCEDURES",
    "DEFAULT_ANALYSIS_EXECUTOR",
    "ExplicitDynamicProcedure",
    "ImplicitDynamicProcedure",
    "LinearStaticProcedure",
    "LinearDynamicProcedure",
    "NonlinearStaticProcedure",
    "PreparedAnalysis",
    "ProcedureContext",
    "RegisteredAnalysisExecutor",
    "analysis_path_for",
    "materialize_incremental_result",
    "AnalysisCancelled",
    "BEAM_SECTION_TYPES",
    "CompiledMaterialAssignment",
    "CompiledMaterialAssignments",
    "CompiledAnalysis",
    "CompiledSystem",
    "CompiledBoundary",
    "EffectiveSectionAssignment",
    "MaterialPropertyError",
    "NonlinearStaticAnalysis",
    "ResolvedSectionAssignment",
    "ResolvedSectionProperties",
    "SECTION_PRESETS",
    "SECTION_TYPES",
    "SectionCompatibilityError",
    "SectionPropertyError",
    "SectionResolution",
    "SectionResolutionIssue",
    "SectionSchemaError",
    "apply_sections",
    "compile_material_assignments",
    "compile_analysis",
    "compile_boundary",
    "check_cancelled",
    "element_section_family",
    "is_nlgeom_enabled",
    "incremental",
    "linear_static",
    "require_nlgeom",
    "resolve_section_properties",
    "resolve_section_preset_properties",
    "resolve_sections",
    "resolve_analysis_request",
    "resolve_execution_plan",
    "resolve_geometry_mode",
    "resolve_formulation",
    "resolve_nlgeom",
    "run_compiled_analysis",
    "restored_element_properties",
    "section_family",
    "section_presets_for_element_family",
    "section_type_for_preset",
    "validate_analysis_step",
    "validate_mesh",
    "validate_model",
    "validate_model_structure",
    "validate_material_properties",
]
