"""Authoring and compiled-model data owned by the CAE model layer.

This package is the canonical home of editable model entities, mesh data,
DOF layout, and typed step controls.  It deliberately contains no solver,
element-operator, result-service, or persistence logic.
"""

from __future__ import annotations

from . import (
    authoring,
    beam_frame,
    beam_section,
    controls,
    entities,
    mesh,
    node_dofs,
    targets,
    units,
)
from .mesh_geometry import line3d_geometry
from .step_queries import effective_displacement_constraints, resolve_analysis_step
from .beam_frame import (
    BEAM_ELEMENT_FRAME_FIELD_KEY,
    BEAM_DEFAULT_LOCAL_Y_REFERENCE,
    BEAM_DEFAULT_LOCAL_Y_REFERENCE_KEY,
    BEAM_ELEMENT_LOCAL_Y_REFERENCE_KEY,
    BEAM_FRAME_COMPARISON_TOLERANCE,
    BEAM_FRAME_FIELD_KEY,
    BEAM_FRAME_FIELD_REFERENCE_KEY,
    BEAM_FRAME_INTEGRATION_ORDER,
    BEAM_FRAME_INTERPOLATION,
    BEAM_LOCAL_Y_REFERENCE_KEY,
    BEAM_ORIENTATION_PARALLEL_TOLERANCE,
    BeamEndFrame,
    BeamFrame,
    BeamFrameField,
    BeamFrameFieldError,
    BeamFrameFieldInvalidError,
    BeamFrameVariationError,
    BeamOrientation,
    BeamOrientationError,
    BeamOrientationInvalidError,
    BeamOrientationParallelError,
    BeamOrientationUnsupportedTargetError,
    parse_beam_orientation,
    resolve_beam_frame,
    resolve_beam_frame_field,
    validate_beam_frame_field,
    validate_beam_frame_fields,
)
from .beam_section import (
    Beam2Section,
    BeamIntegrationPointForces,
    BeamSectionEndActions,
    BeamSectionPoint,
    BeamSectionPointStress,
    parse_beam2_section,
)
from .authoring import add_material, assign_section, transient_dynamic
from .controls import (
    DampingModel,
    DynamicIntegrationMethod,
    DynamicProcedureKind,
    DynamicStepControls,
    GeometryMode,
    InitialConditionSet,
    MassMatrixPolicy,
    NewtonStrategy,
    ProcedureControls,
    StaticAnalysisOptions,
    StaticControlMode,
    StaticFormulation,
    StaticStepControls,
    TimeAmplitude,
)
from .units import UnitContext
from .node_dofs import NodeDofMap
from .dof_space import DofSpace, FieldDofs
from .entities import (
    AnalysisStep,
    AnalysisStepSnapshot,
    BodyForce,
    DisplacementConstraint,
    Edge,
    EdgeLoad,
    ElementEdge,
    ElementFace,
    ElementInfo,
    ElementSet,
    FEMModel,
    GravityLoad,
    LineLoad,
    MaterialBehavior,
    MaterialDefinition,
    NodalLoad,
    NodeSet,
    OutputRequest,
    OutputSourceEvidence,
    SectionAssignment,
    Surface,
    SurfaceLoad,
    model_element_info,
)
from .mesh import (
    Element2D,
    Element3D,
    Mesh2D,
    Mesh3D,
    MeshProtocol,
    Node2D,
    Node3D,
)
from .validation import validate_mesh

__all__ = [
    "AnalysisStep",
    "AnalysisStepSnapshot",
    "add_material",
    "authoring",
    "BEAM_DEFAULT_LOCAL_Y_REFERENCE",
    "BEAM_DEFAULT_LOCAL_Y_REFERENCE_KEY",
    "BEAM_ELEMENT_FRAME_FIELD_KEY",
    "BEAM_ELEMENT_LOCAL_Y_REFERENCE_KEY",
    "BEAM_FRAME_COMPARISON_TOLERANCE",
    "BEAM_FRAME_FIELD_KEY",
    "BEAM_FRAME_FIELD_REFERENCE_KEY",
    "BEAM_FRAME_INTEGRATION_ORDER",
    "BEAM_FRAME_INTERPOLATION",
    "BEAM_LOCAL_Y_REFERENCE_KEY",
    "BEAM_ORIENTATION_PARALLEL_TOLERANCE",
    "Beam2Section",
    "BeamEndFrame",
    "BeamFrame",
    "BeamFrameField",
    "BeamFrameFieldError",
    "BeamFrameFieldInvalidError",
    "BeamFrameVariationError",
    "BeamIntegrationPointForces",
    "BeamOrientation",
    "BeamOrientationError",
    "BeamOrientationInvalidError",
    "BeamOrientationParallelError",
    "BeamOrientationUnsupportedTargetError",
    "BeamSectionEndActions",
    "BeamSectionPoint",
    "BeamSectionPointStress",
    "BodyForce",
    "DampingModel",
    "DynamicIntegrationMethod",
    "DynamicProcedureKind",
    "DynamicStepControls",
    "DisplacementConstraint",
    "NodeDofMap",
    "DofSpace",
    "Edge",
    "EdgeLoad",
    "Element2D",
    "Element3D",
    "ElementEdge",
    "ElementFace",
    "ElementInfo",
    "ElementSet",
    "effective_displacement_constraints",
    "FEMModel",
    "FieldDofs",
    "GeometryMode",
    "InitialConditionSet",
    "NewtonStrategy",
    "GravityLoad",
    "LineLoad",
    "MaterialBehavior",
    "MaterialDefinition",
    "MassMatrixPolicy",
    "Mesh2D",
    "Mesh3D",
    "MeshProtocol",
    "NodalLoad",
    "Node2D",
    "Node3D",
    "NodeSet",
    "OutputRequest",
    "OutputSourceEvidence",
    "ProcedureControls",
    "SectionAssignment",
    "assign_section",
    "transient_dynamic",
    "StaticStepControls",
    "TimeAmplitude",
    "StaticAnalysisOptions",
    "StaticControlMode",
    "StaticFormulation",
    "UnitContext",
    "Surface",
    "SurfaceLoad",
    "controls",
    "beam_frame",
    "beam_section",
    "node_dofs",
    "entities",
    "mesh",
    "model_element_info",
    "line3d_geometry",
    "parse_beam2_section",
    "parse_beam_orientation",
    "resolve_beam_frame",
    "resolve_beam_frame_field",
    "resolve_analysis_step",
    "targets",
    "units",
    "validate_mesh",
    "validate_beam_frame_field",
    "validate_beam_frame_fields",
]
