"""Headless application lifecycle contracts for FEM front ends."""

from fem.elements import BeamOrientation

from .beam_frames import (
    BeamFrameReport,
    EffectiveBeamFrame,
    resolve_effective_beam_frames,
)
from .changes import ArtifactKind, ChangeKind, SessionDelta
from .capabilities import (
    AuthoringCapability,
    AuthoringStatus,
    ModelCapabilityReport,
    RegionCapability,
    RegionRef,
    describe_model_capabilities,
    describe_native_authoring_capabilities,
    describe_region_capabilities,
    evaluate_authoring_candidate,
    require_region_kind,
)
from .definitions import (
    DefinitionCompileResult,
    DefinitionRejected,
    FeatureRecord,
    ModelDefinitions,
    NamedRegion,
    NativePart,
    RegionAssignment,
    SectionDefinition,
    compile_model_definitions,
    compiled_model_snapshot,
    definitions_from_model,
    normalize_model_definitions,
)
from .feature_history import (
    derive_feature_history,
    derive_geometry_feature_rows,
)
from .native_regions import (
    CompiledDomainRegionSource,
    LogicalReferencesRegionSource,
    NativeRegionDescriptor,
    NativeRegionProduct,
    NativeRegionSource,
    NativeRegionValidationError,
    RecipeRegionSelector,
    RecipeRegionSource,
    describe_native_regions,
    require_native_region_product,
    validate_logical_reference,
    validate_logical_references,
    validate_native_authoring_context,
)
from .diagnostics import (
    PreflightDiagnostic,
    PreflightFacts,
    PreflightReport,
    PreflightSeverity,
    PreflightStage,
    internal_error_report,
)
from .revisions import (
    ImportTaskSnapshot,
    MeshTaskSnapshot,
    ModelArtifact,
    ResultProjectionTaskSnapshot,
    ResultTaskSnapshot,
    SolveTaskSnapshot,
    TaskToken,
    TokenStatus,
    ValidationTaskSnapshot,
)
from .runs import (
    AnalysisRun,
    ResultProvenance,
    ResultRecord,
    RunStatus,
)
from .preprocessing import (
    LogicalRecipeTopologyResolver,
    TopologyResolutionError,
    generate_fem_model,
)
from .preflight import run_static_preflight, safe_static_preflight
from .project_validation import (
    analysis_step_has_native_region_target,
    analysis_steps_have_native_region_targets,
)
from .session import (
    ModelSession,
    ProjectSaveSnapshot,
    ProjectSnapshot,
    RevisionConflictError,
    SessionSnapshot,
    SessionStateError,
)
from .validation import ValidationRecord, ValidationStamp

__all__ = [
    "AnalysisRun",
    "ArtifactKind",
    "AuthoringCapability",
    "AuthoringStatus",
    "BeamFrameReport",
    "BeamOrientation",
    "ChangeKind",
    "CompiledDomainRegionSource",
    "DefinitionCompileResult",
    "DefinitionRejected",
    "EffectiveBeamFrame",
    "FeatureRecord",
    "ImportTaskSnapshot",
    "LogicalRecipeTopologyResolver",
    "LogicalReferencesRegionSource",
    "MeshTaskSnapshot",
    "ModelArtifact",
    "ModelCapabilityReport",
    "ModelDefinitions",
    "ModelSession",
    "NamedRegion",
    "NativePart",
    "NativeRegionDescriptor",
    "NativeRegionProduct",
    "NativeRegionSource",
    "NativeRegionValidationError",
    "ProjectSaveSnapshot",
    "ProjectSnapshot",
    "PreflightDiagnostic",
    "PreflightFacts",
    "PreflightReport",
    "PreflightSeverity",
    "PreflightStage",
    "RegionAssignment",
    "RegionCapability",
    "RegionRef",
    "RecipeRegionSelector",
    "RecipeRegionSource",
    "ResultProjectionTaskSnapshot",
    "ResultProvenance",
    "ResultRecord",
    "ResultTaskSnapshot",
    "RevisionConflictError",
    "RunStatus",
    "SectionDefinition",
    "SessionDelta",
    "SessionSnapshot",
    "SessionStateError",
    "SolveTaskSnapshot",
    "TaskToken",
    "TopologyResolutionError",
    "TokenStatus",
    "ValidationRecord",
    "ValidationStamp",
    "ValidationTaskSnapshot",
    "analysis_step_has_native_region_target",
    "analysis_steps_have_native_region_targets",
    "compile_model_definitions",
    "compiled_model_snapshot",
    "describe_model_capabilities",
    "describe_native_regions",
    "describe_native_authoring_capabilities",
    "describe_region_capabilities",
    "evaluate_authoring_candidate",
    "derive_feature_history",
    "derive_geometry_feature_rows",
    "definitions_from_model",
    "generate_fem_model",
    "internal_error_report",
    "normalize_model_definitions",
    "require_native_region_product",
    "require_region_kind",
    "resolve_effective_beam_frames",
    "run_static_preflight",
    "safe_static_preflight",
    "validate_logical_reference",
    "validate_logical_references",
    "validate_native_authoring_context",
]
