"""Public scripted-geometry API."""

from __future__ import annotations

from .errors import (
    EntityOwnershipError,
    GeometryError,
    GeometryStateError,
    StaleEntityError,
)
from .recipe_analysis import (
    CircleFrame,
    RectangleFrame,
    axis_aligned_rectangle,
    expand_sketch_recipe,
    recipe_characteristic_size,
    supports_structured_hexahedron,
    transformed_circle,
)
from .recipes import (
    BASE_GEOMETRY_TYPES,
    BooleanGeometry,
    BoxGeometry,
    CylinderGeometry,
    DiskGeometry,
    ExtrudedGeometry,
    MovedGeometry,
    NATIVE_GEOMETRY_TYPES,
    NativeGeometry,
    PRIMITIVE_GEOMETRY_TYPES,
    PlateWithHoleGeometry,
    PrimitiveGeometry,
    RectangleGeometry,
    RotatedGeometry,
    SKETCH_CONTOUR_TYPES,
    SketchCircle,
    SketchContour,
    SketchGeometry,
    SketchRectangle,
    WireGeometry,
    WireMember,
    WirePoint,
    geometry_dimension,
)
from .measurements import (
    TargetRadiusResolutionError,
    resolve_legacy_hole_target,
    resolve_target_radius,
)
from .references import EntityKind, LogicalEntityRef, logical_ref_sort_key
from .types import (
    BooleanResult,
    CurveLoopRef,
    EntityRef,
    FeatureResult,
    LoftContinuity,
    LoftParametrization,
    LoftResult,
    OrientedCurveRef,
    SweepFrame,
    WireRef,
)
from ._gmsh.model import GeometryModel, model

__all__ = [
    "BASE_GEOMETRY_TYPES",
    "BooleanResult",
    "BooleanGeometry",
    "BoxGeometry",
    "CircleFrame",
    "CurveLoopRef",
    "CylinderGeometry",
    "DiskGeometry",
    "EntityOwnershipError",
    "EntityKind",
    "EntityRef",
    "ExtrudedGeometry",
    "FeatureResult",
    "GeometryError",
    "GeometryModel",
    "GeometryStateError",
    "LoftContinuity",
    "LoftParametrization",
    "LoftResult",
    "LogicalEntityRef",
    "MovedGeometry",
    "NATIVE_GEOMETRY_TYPES",
    "NativeGeometry",
    "OrientedCurveRef",
    "PRIMITIVE_GEOMETRY_TYPES",
    "PlateWithHoleGeometry",
    "PrimitiveGeometry",
    "RectangleFrame",
    "RectangleGeometry",
    "RotatedGeometry",
    "SKETCH_CONTOUR_TYPES",
    "SketchCircle",
    "SketchContour",
    "SketchGeometry",
    "SketchRectangle",
    "StaleEntityError",
    "SweepFrame",
    "TargetRadiusResolutionError",
    "WireRef",
    "WireGeometry",
    "WireMember",
    "WirePoint",
    "axis_aligned_rectangle",
    "expand_sketch_recipe",
    "geometry_dimension",
    "logical_ref_sort_key",
    "model",
    "recipe_characteristic_size",
    "resolve_legacy_hole_target",
    "resolve_target_radius",
    "supports_structured_hexahedron",
    "transformed_circle",
]
