from __future__ import annotations

from dataclasses import dataclass
import math
import operator
from typing import Any, Literal

from fem.core import (
    Element2D,
    Element3D,
    Mesh2D,
    Mesh3D,
    Node2D,
    Node3D,
)
from fem.mesh.gmsh import GmshMeshRef


@dataclass(frozen=True)
class _ElementSpec:
    gmsh_type: int
    gmsh_name: str
    dimension: Literal[1, 2, 3]
    order: int
    node_count: int
    primary_node_count: int
    fem_type: str | None
    connectivity_permutation: tuple[int, ...]


@dataclass(frozen=True)
class _ElementRecord:
    element_id: int
    spec: _ElementSpec
    node_ids: tuple[int, ...]


def _validated_element_specs(specs: tuple[_ElementSpec, ...]) -> dict[int, _ElementSpec]:
    validated: dict[int, _ElementSpec] = {}
    for spec in specs:
        if spec.gmsh_type in validated:
            raise RuntimeError(f"duplicate Gmsh element specification {spec.gmsh_type}")
        if sorted(spec.connectivity_permutation) != list(range(spec.node_count)):
            raise RuntimeError(
                f"invalid connectivity permutation for Gmsh element type "
                f"{spec.gmsh_type}: {spec.connectivity_permutation!r}"
            )
        validated[spec.gmsh_type] = spec
    return validated


_ELEMENT_SPECS = _validated_element_specs(
    (
        _ElementSpec(1, "Line 2", 1, 1, 2, 2, None, (0, 1)),
        _ElementSpec(2, "Triangle 3", 2, 1, 3, 3, "Tri3", (0, 1, 2)),
        _ElementSpec(
            3,
            "Quadrilateral 4",
            2,
            1,
            4,
            4,
            "Quad4",
            (0, 1, 2, 3),
        ),
        _ElementSpec(4, "Tetrahedron 4", 3, 1, 4, 4, "Tet4", (0, 1, 2, 3)),
        _ElementSpec(
            5,
            "Hexahedron 8",
            3,
            1,
            8,
            8,
            "Hex8",
            (0, 1, 2, 3, 4, 5, 6, 7),
        ),
        _ElementSpec(9, "Triangle 6", 2, 2, 6, 3, "Tri6", (0, 1, 2, 3, 4, 5)),
        _ElementSpec(
            16,
            "Quadrilateral 8",
            2,
            2,
            8,
            4,
            "Quad8",
            (0, 1, 2, 3, 4, 5, 6, 7),
        ),
        _ElementSpec(
            11,
            "Tetrahedron 10",
            3,
            2,
            10,
            4,
            "Tet10",
            (0, 1, 2, 3, 4, 5, 6, 7, 9, 8),
        ),
        _ElementSpec(
            17,
            "Hexahedron 20",
            3,
            2,
            20,
            8,
            "Hex20",
            (
                0,
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                11,
                13,
                9,
                16,
                18,
                19,
                17,
                10,
                12,
                14,
                15,
            ),
        ),
    )
)


_CLOCKWISE_TO_COUNTERCLOCKWISE = {
    "Tri3": (0, 2, 1),
    "Tri6": (0, 2, 1, 5, 4, 3),
    "Quad4": (0, 3, 2, 1),
    "Quad8": (0, 3, 2, 1, 7, 6, 5, 4),
}

_INCOMPLETE_SECOND_ORDER_ALTERNATIVES = {
    10: ("Quadrilateral 9", "Quad8"),
    12: ("Hexahedron 27", "Hex20"),
}


def read(
    source: GmshMeshRef,
    *,
    line_element_type: Literal["Truss2", "Beam2"] | None = None,
    plane_type: Literal["stress", "strain"] = "stress",
    thickness: float = 1.0,
    z_tolerance: float = 1e-10,
) -> Mesh2D | Mesh3D:
    """Convert a live mesh generated by :mod:`fem.mesh.gmsh`."""
    if not isinstance(source, GmshMeshRef):
        raise TypeError(
            "source must be a GmshMeshRef returned by "
            "fem.mesh.gmsh.Mesher.generate()"
        )

    dimension = _validate_dimension(source.dimension)
    normalized_line_element_type = _validate_line_element_type(
        dimension,
        line_element_type,
    )
    normalized_plane_type = _validate_plane_type(plane_type)
    normalized_thickness = _validate_thickness(thickness)
    normalized_z_tolerance = _validate_z_tolerance(z_tolerance)
    gmsh_model = GmshMeshRef._borrow_model(source)
    return _from_backend(
        gmsh_model,
        dimension=dimension,
        line_element_type=normalized_line_element_type,
        plane_type=normalized_plane_type,
        thickness=normalized_thickness,
        z_tolerance=normalized_z_tolerance,
    )


def from_model(
    *,
    dimension: Literal[1, 2, 3],
    gmsh_model: Any | None = None,
    line_element_type: Literal["Truss2", "Beam2"] | None = None,
    plane_type: Literal["stress", "strain"] = "stress",
    thickness: float = 1.0,
    z_tolerance: float = 1e-10,
) -> Mesh2D | Mesh3D:
    """Import the generated mesh from a caller-owned active Gmsh model."""
    normalized_dimension = _validate_dimension(dimension)
    normalized_line_element_type = _validate_line_element_type(
        normalized_dimension,
        line_element_type,
    )
    normalized_plane_type = _validate_plane_type(plane_type)
    normalized_thickness = _validate_thickness(thickness)
    normalized_z_tolerance = _validate_z_tolerance(z_tolerance)

    if gmsh_model is None:
        gmsh_model = _resolve_live_backend()

    return _from_backend(
        gmsh_model,
        dimension=normalized_dimension,
        line_element_type=normalized_line_element_type,
        plane_type=normalized_plane_type,
        thickness=normalized_thickness,
        z_tolerance=normalized_z_tolerance,
    )


def _resolve_live_backend() -> Any:
    try:
        import gmsh
    except ModuleNotFoundError as exc:
        if exc.name != "gmsh":
            raise
        raise ModuleNotFoundError(
            "Gmsh is an optional dependency; install it with "
            "`python -m pip install -e .[cad]`."
        ) from exc

    if not gmsh.isInitialized():
        raise RuntimeError(
            "Gmsh is not initialized; the caller must call gmsh.initialize() "
            "before fem.io.gmsh.from_model()."
        )

    return gmsh.model


def _validate_dimension(value: Any) -> Literal[1, 2, 3]:
    if isinstance(value, bool) or not isinstance(value, int) or value not in (1, 2, 3):
        raise ValueError(f"dimension must be 1, 2, or 3, got {value!r}")
    return value


def _validate_line_element_type(
    dimension: Literal[1, 2, 3],
    value: Any,
) -> Literal["Truss2", "Beam2"] | None:
    if dimension == 1:
        if value not in ("Truss2", "Beam2"):
            raise ValueError(
                "line_element_type must be exactly 'Truss2' or 'Beam2' for "
                f"dimension 1, got {value!r}"
            )
        return value
    if value is not None:
        raise ValueError(
            "line_element_type is only valid for dimension 1, "
            f"got {value!r} for dimension {dimension}"
        )
    return None


def _validate_plane_type(value: Any) -> str:
    if not isinstance(value, str) or value.lower() not in {"stress", "strain"}:
        raise ValueError(
            f"plane_type must be 'stress' or 'strain', got {value!r}"
        )
    return value.lower()


def _validate_thickness(value: Any) -> float:
    try:
        normalized = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"thickness must be finite and > 0, got {value!r}") from exc
    if not math.isfinite(normalized) or normalized <= 0.0:
        raise ValueError(f"thickness must be finite and > 0, got {value!r}")
    return normalized


def _validate_z_tolerance(value: Any) -> float:
    try:
        normalized = float(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(
            f"z_tolerance must be finite and >= 0, got {value!r}"
        ) from exc
    if not math.isfinite(normalized) or normalized < 0.0:
        raise ValueError(f"z_tolerance must be finite and >= 0, got {value!r}")
    return normalized


def _from_backend(
    gmsh_model: Any,
    *,
    dimension: Literal[1, 2, 3],
    line_element_type: Literal["Truss2", "Beam2"] | None,
    plane_type: str,
    thickness: float,
    z_tolerance: float,
) -> Mesh2D | Mesh3D:
    records = _read_element_records(gmsh_model.mesh, dimension)
    referenced_node_ids = {
        node_id for record in records for node_id in record.node_ids
    }
    nodes, coordinates = _read_nodes(
        gmsh_model.mesh,
        referenced_node_ids,
        dimension=dimension,
        z_tolerance=z_tolerance,
    )
    elements = _build_elements(
        records,
        coordinates,
        dimension=dimension,
        line_element_type=line_element_type,
        plane_type=plane_type,
        thickness=thickness,
    )
    if dimension == 2:
        return Mesh2D(nodes=nodes, elements=elements, dofs_per_node=2)
    if dimension == 1:
        dofs_per_node = 3 if line_element_type == "Truss2" else 6
        return Mesh3D(nodes=nodes, elements=elements, dofs_per_node=dofs_per_node)
    return Mesh3D(nodes=nodes, elements=elements, dofs_per_node=3)


def _read_element_records(
    gmsh_mesh: Any,
    dimension: Literal[1, 2, 3],
) -> list[_ElementRecord]:
    raw_blocks = gmsh_mesh.getElements(dimension, -1)
    try:
        raw_types, raw_element_tags, raw_connectivity = raw_blocks
    except (TypeError, ValueError) as exc:
        raise ValueError(
            "getElements() must return element types, element-tag blocks, "
            "and connectivity blocks"
        ) from exc

    element_types = list(raw_types)
    element_tag_blocks = list(raw_element_tags)
    connectivity_blocks = list(raw_connectivity)
    block_count = len(element_types)
    if len(element_tag_blocks) != block_count or len(connectivity_blocks) != block_count:
        raise ValueError(
            "getElements() returned inconsistent element block counts: "
            f"{block_count} types, {len(element_tag_blocks)} element-tag blocks, "
            f"and {len(connectivity_blocks)} connectivity blocks"
        )

    records: list[_ElementRecord] = []
    seen_element_ids: set[int] = set()
    for block_index, (raw_type, raw_tags, raw_nodes) in enumerate(
        zip(element_types, element_tag_blocks, connectivity_blocks, strict=True)
    ):
        element_type = _integer_value(raw_type, "Gmsh element types must be integers")
        reported = _reported_element_properties(gmsh_mesh, element_type)
        spec = _ELEMENT_SPECS.get(element_type)
        if spec is None:
            name, reported_dimension, order, node_count, primary_node_count = reported
            message = (
                f"unsupported Gmsh element type {element_type} ({name!r}, "
                f"dimension={reported_dimension}, order={order}, nodes={node_count}, "
                f"primary_nodes={primary_node_count})"
            )
            alternative = _INCOMPLETE_SECOND_ORDER_ALTERNATIVES.get(element_type)
            if alternative is not None and name == alternative[0]:
                message += (
                    f". {name} is unsupported because FEM-Python provides "
                    f"{alternative[1]}. Generate an incomplete second-order mesh "
                    f"with Mesh.SecondOrderIncomplete = 1."
                )
            if dimension == 1 and element_type == 8 and name == "Line 3":
                message += (
                    ". FEM-Python's current Truss2 and Beam2 formulations "
                    "support only first-order, two-node line elements."
                )
            raise ValueError(message)
        expected = (
            spec.gmsh_name,
            spec.dimension,
            spec.order,
            spec.node_count,
            spec.primary_node_count,
        )
        if reported != expected:
            raise ValueError(
                f"Gmsh element type {element_type} properties do not match the "
                f"adapter contract: reported {reported!r}, expected {expected!r}"
            )
        if spec.dimension != dimension:
            raise ValueError(
                f"Gmsh element type {element_type} has dimension {spec.dimension}, "
                f"but dimension {dimension} was requested"
            )

        element_ids = [
            _positive_tag(value, "element tags") for value in list(raw_tags)
        ]
        flat_node_ids = [
            _positive_tag(value, "connectivity node tags")
            for value in list(raw_nodes)
        ]
        expected_connectivity_count = len(element_ids) * spec.node_count
        if len(flat_node_ids) != expected_connectivity_count:
            raise ValueError(
                f"Gmsh element block {block_index} type {element_type} flattened "
                f"connectivity has length {len(flat_node_ids)}; expected "
                f"{expected_connectivity_count} for {len(element_ids)} elements "
                f"with {spec.node_count} nodes each"
            )

        for local_element_index, element_id in enumerate(element_ids):
            if element_id in seen_element_ids:
                raise ValueError(f"duplicate element tag {element_id} across blocks")
            seen_element_ids.add(element_id)
            start = local_element_index * spec.node_count
            raw_node_ids = flat_node_ids[start : start + spec.node_count]
            node_ids = tuple(
                raw_node_ids[index] for index in spec.connectivity_permutation
            )
            if len(set(node_ids)) != len(node_ids):
                raise ValueError(
                    f"Gmsh element {element_id} type {element_type} has repeated "
                    f"node tags {node_ids!r}"
                )
            records.append(_ElementRecord(element_id, spec, node_ids))

    if not records:
        raise ValueError(
            f"Gmsh model contains no top-dimensional elements for dimension {dimension}"
        )
    return records


def _reported_element_properties(
    gmsh_mesh: Any,
    element_type: int,
) -> tuple[str, int, int, int, int]:
    properties = gmsh_mesh.getElementProperties(element_type)
    try:
        name, dimension, order, node_count = properties[:4]
        primary_node_count = properties[5]
    except (IndexError, TypeError, ValueError) as exc:
        raise ValueError(
            f"getElementProperties({element_type}) returned malformed data"
        ) from exc
    return (
        str(name),
        _integer_value(dimension, "reported element dimension must be an integer"),
        _integer_value(order, "reported element order must be an integer"),
        _integer_value(node_count, "reported element node count must be an integer"),
        _integer_value(
            primary_node_count,
            "reported primary node count must be an integer",
        ),
    )


def _read_nodes(
    gmsh_mesh: Any,
    referenced_node_ids: set[int],
    *,
    dimension: Literal[1, 2, 3],
    z_tolerance: float,
) -> tuple[list[Node2D] | list[Node3D], dict[int, tuple[float, float, float]]]:
    raw_nodes = gmsh_mesh.getNodes()
    try:
        raw_node_tags, raw_coordinates = raw_nodes[:2]
    except (TypeError, ValueError) as exc:
        raise ValueError(
            "getNodes() must return node tags and a flattened coordinate vector"
        ) from exc

    node_ids: list[int] = []
    seen_node_ids: set[int] = set()
    for raw_node_id in list(raw_node_tags):
        node_id = _positive_tag(raw_node_id, "node tags")
        if node_id in seen_node_ids:
            raise ValueError(f"duplicate node tag {node_id}")
        seen_node_ids.add(node_id)
        node_ids.append(node_id)

    raw_coordinate_values = list(raw_coordinates)
    expected_coordinate_count = 3 * len(node_ids)
    if len(raw_coordinate_values) != expected_coordinate_count:
        raise ValueError(
            f"Gmsh node coordinate vector length is {len(raw_coordinate_values)}; "
            f"expected {expected_coordinate_count} for {len(node_ids)} node tags"
        )
    coordinates: list[float] = []
    for value in raw_coordinate_values:
        try:
            coordinate = float(value)
        except (TypeError, ValueError) as exc:
            raise ValueError("Gmsh node coordinates must be finite numbers") from exc
        if not math.isfinite(coordinate):
            raise ValueError("Gmsh node coordinates must be finite numbers")
        coordinates.append(coordinate)

    coordinate_by_node = {
        node_id: tuple(coordinates[index : index + 3])
        for index, node_id in zip(range(0, len(coordinates), 3), node_ids, strict=True)
    }
    missing_node_ids = sorted(referenced_node_ids.difference(coordinate_by_node))
    if missing_node_ids:
        raise ValueError(f"element references missing node tag {missing_node_ids[0]}")

    retained_nodes: list[Node2D] | list[Node3D] = []
    for node_id in node_ids:
        if node_id not in referenced_node_ids:
            continue
        x, y, z = coordinate_by_node[node_id]
        if dimension == 2:
            if abs(z) > z_tolerance:
                raise ValueError(
                    f"Gmsh node {node_id} has z={z!r} outside the XY-plane "
                    f"tolerance {z_tolerance!r}"
                )
            retained_nodes.append(Node2D(node_id, x, y))
        else:
            retained_nodes.append(Node3D(node_id, x, y, z))
    return retained_nodes, coordinate_by_node


def _build_elements(
    records: list[_ElementRecord],
    coordinates: dict[int, tuple[float, float, float]],
    *,
    dimension: Literal[1, 2, 3],
    line_element_type: Literal["Truss2", "Beam2"] | None,
    plane_type: str,
    thickness: float,
) -> list[Element2D] | list[Element3D]:
    if dimension in (1, 3):
        fem_types = [
            line_element_type if dimension == 1 else record.spec.fem_type
            for record in records
        ]
        if any(fem_type is None for fem_type in fem_types):
            raise RuntimeError("Gmsh element specification has no FEM element type")
        return [
            Element3D(
                record.element_id,
                list(record.node_ids),
                fem_type,
                {},
            )
            for record, fem_type in zip(records, fem_types, strict=True)
        ]

    elements_2d: list[Element2D] = []
    props = {"plane_type": plane_type, "thickness": thickness}
    for record in records:
        node_ids = list(record.node_ids)
        corner_node_ids = node_ids[: record.spec.primary_node_count]
        if _signed_twice_area(corner_node_ids, coordinates) < 0.0:
            permutation = _CLOCKWISE_TO_COUNTERCLOCKWISE[record.spec.fem_type]
            node_ids = [node_ids[index] for index in permutation]
        elements_2d.append(
            Element2D(
                record.element_id,
                node_ids,
                record.spec.fem_type,
                dict(props),
            )
        )
    return elements_2d


def _signed_twice_area(
    node_ids: list[int],
    coordinates: dict[int, tuple[float, float, float]],
) -> float:
    area = 0.0
    for index, node_id in enumerate(node_ids):
        next_node_id = node_ids[(index + 1) % len(node_ids)]
        x, y, _ = coordinates[node_id]
        next_x, next_y, _ = coordinates[next_node_id]
        area += x * next_y - next_x * y
    return area


def _integer_value(value: Any, message: str) -> int:
    try:
        return operator.index(value)
    except TypeError as exc:
        raise ValueError(message) from exc


def _positive_tag(value: Any, label: str) -> int:
    try:
        tag = operator.index(value)
    except TypeError as exc:
        raise ValueError(f"{label} must be positive integers") from exc
    if tag <= 0:
        raise ValueError(f"{label} must be positive integers")
    return tag


__all__ = ["read", "from_model"]
